import { Inter } from "next/font/google";
import "./globals.css";

import QueryProvider from "../shared/api/QueryProvider";
import { Toaster } from "@/shared/ui/sonner";

// Подключаем шрифт Inter
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased h-screen flex flex-col`} // Добавляем переменную шрифта
      >
        <QueryProvider>
          {/* <Header /> */}
          {children}
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
